WeatherMSN: downloadPage requires bytes
Fixes the following error:`
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 58, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 146, in save
    self.run()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 150, in run
    plugin.__call__(session=self.session)
  File "/usr/lib/enigma2/python/Plugins/Extensions/WeatherMSN/plugin.py", line 2897, in main
    session.open(WeatherMSN)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 316, in open
    self.execBegin()
  File "/usr/lib/enigma2/python/StartEnigma.py", line 241, in execBegin
    c.show()
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 129, in show
    x()
  File "/usr/lib/enigma2/python/Plugins/Extensions/WeatherMSN/plugin.py", line 671, in get_weather_data
    self.get_xmlfile()
  File "/usr/lib/enigma2/python/Plugins/Extensions/WeatherMSN/plugin.py", line 658, in get_xmlfile
    downloadPage(xmlfile, "/tmp/weathermsn1.xml").addCallback(self.downloadFinished).addErrback(self.downloadFailed)
  File "/usr/lib/python3.9/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/twisted/web/client.py", line 829, in downloadPage
    return _makeGetterFactory(
  File "/usr/lib/python3.9/site-packages/twisted/web/client.py", line 760, in _makeGetterFactory
    uri = URI.fromBytes(_ensureValidURI(url.strip()))
  File "/usr/lib/python3.9/site-packages/twisted/web/_newclient.py", line 634, in _ensureValidURI
    if _VALID_URI.match(uri):
TypeError: cannot use a bytes pattern on a string-like object